// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4BA8Pg2mR_P4IyHLFPq1nR1vCcbVVe4',
    appId: '1:1032547867597:web:d0458215a72df4d1770284',
    messagingSenderId: '1032547867597',
    projectId: 'cl-vault',
    authDomain: 'cl-vault.firebaseapp.com',
    storageBucket: 'cl-vault.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCaE52-yhC8YGRVd6rXjU4D0n-ztyqhMo',
    appId: '1:1032547867597:android:9ef56ebb2409b52f770284',
    messagingSenderId: '1032547867597',
    projectId: 'cl-vault',
    storageBucket: 'cl-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr4hdbL4WqMONiRhY1T82VpZ0hhcO4Uac',
    appId: '1:1032547867597:ios:df205c7667001c91770284',
    messagingSenderId: '1032547867597',
    projectId: 'cl-vault',
    storageBucket: 'cl-vault.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr4hdbL4WqMONiRhY1T82VpZ0hhcO4Uac',
    appId: '1:1032547867597:ios:df205c7667001c91770284',
    messagingSenderId: '1032547867597',
    projectId: 'cl-vault',
    storageBucket: 'cl-vault.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4BA8Pg2mR_P4IyHLFPq1nR1vCcbVVe4',
    appId: '1:1032547867597:web:6e18ad189d1ebe03770284',
    messagingSenderId: '1032547867597',
    projectId: 'cl-vault',
    authDomain: 'cl-vault.firebaseapp.com',
    storageBucket: 'cl-vault.firebasestorage.app',
  );
}
